### ISSUE TITLE
关于模型开源

### ISSUE THREAD

**Issue by Lipurple** [colorful-liyu/anyfit-page#1]
同学您好～想问这个工作会有后续代码开源的计划嘛

**Comment by colorful-liyu** [comment]
你好，实习期间所得成果均归属公司，关于AnyFit的代码发布问题，我的主管以及公司法务正在研究，我目前尚不清楚他们的结论。我无法私下发布模型的代码及模型，望体谅！

**Comment by colorful-liyu** [comment]
你好，实习期间所得成果均归属公司，关于AnyFit的代码发布问题，我的主管以及公司法务正在研究，我目前尚不清楚他们的结论。我无法私下发布模型的代码及模型，望体谅！
